\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={Data Journalism - A Quick \& Practical Guide},
            pdfauthor={Rob Wells - thanks to Yihui Xie},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Fix footnotes in tables (requires footnote package)
\IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{longtable}}{}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{booktabs}
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage[]{natbib}
\bibliographystyle{apalike}

\title{Data Journalism - A Quick \& Practical Guide}
\author{Rob Wells - thanks to Yihui Xie}
\date{2021-06-02}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{data-journalism---a-quick-practical-guide}{%
\chapter*{Data Journalism - A Quick \& Practical Guide}\label{data-journalism---a-quick-practical-guide}}
\addcontentsline{toc}{chapter}{Data Journalism - A Quick \& Practical Guide}

\includegraphics{Images/UARK logo NEW.png}

\textbf{Rob Wells, Ph.D.}\\
\href{mailto:rswells@uark.edu}{\nolinkurl{rswells@uark.edu}}\\
Twitter: rwells1961

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\textbf{Inspiration:}\\

Mapping in Tableau

Please review this mapping tutorialbasic-mapping-transcriptSample WorkbookVideos: https://www.tableau.com/learn/tutorials/on-demand/getting-started-mapping?playlist=230855

Build a Map COVID-19 Positivity in Arkansas CountiesData: County data for one day.

--Import the countyonlytoday.csv data as text into Tableau--Check the geographic role of county is assigned to county.--Go to Sheet 1:a) drag Longitude to columnsb) Latitude to rowsc) County Name to the pane--A map of Arkansas appears.d) In top Menu: MAP \textbar{} Edit Locations \textbar{} State / Province \textbar{} Fixed - Select the great state of Arkansas--The map now has all counties represented as dotse) In Marks card: Change Automatic to Mapf) drag Positive to the pane - you now have a map of positive rates by county.Video below with all of these steps:

Dual Mapping - Bubble Maps

Tutorialhttps://onlinehelp.tableau.com/current/pro/desktop/en-us/maps\_dualaxis.htmlUsing countyonlytoday.csv

New sheet, begin map: Drag counties to mapFix the missing counties: Map \textbar{} Edit Locations \textbar{} Fixed \textbar{} ArkansasMarks Card \textbar{} MapDrag Deaths map

{Here's where it is tricky}:

Click on Longitude pill in Columns. Press Command key. Drag to Right. Release mouse--Creates two Longitude pills and two maps--Marks Card Now Has Controls for Two MapsMarks Card Has Two Maps.~Lower Map, Drag off color pill. Marks Card, switch to Circle.Drag Deaths to Size. Enlarge the CirclesDrag Deaths to Labels.

In Columns, Select Down Arrow on Longitude \textbar{} Dual Axis--Maps are combined~Drag County to Marks Card \textbar{} TooltipEdit Tooltips so data displays properly

\textbf{Teams}

\begin{verbatim}
  For the first class, please have Teams installed so we can do some exercises.    
  Teams is free through your university Office365 account. Download the Teams App through the Office365 suite.
\end{verbatim}

\url{https://its.uark.edu/communication-collaboration/office365/office365-desktop-apps.php}

\textbf{Teams Videos}

\begin{verbatim}
  Microsoft Teams allows us to easily share information through the class or in discrete groups.
  
  Chat in Teams
\end{verbatim}

\url{https://www.microsoft.com/en-us/videoplayer/embed/RE4rLgJ?pid=ocpVideo5-innerdiv-oneplayer\&postJsllMsg=true\&maskLevel=20\&market=en-us}

\begin{verbatim}
  Create a post
\end{verbatim}

\url{https://www.microsoft.com/en-us/videoplayer/embed/RE2BIrO?pid=ocpVideo0-innerdiv-oneplayer\&postJsllMsg=true\&maskLevel=20\&market=en-us}

\begin{verbatim}
  How to tag a person in Teams
\end{verbatim}

\url{https://www.microsoft.com/en-us/videoplayer/embed/RWkJ9C?pid=ocpVideo0-innerdiv-oneplayer\&postJsllMsg=true\&maskLevel=20\&market=en-us}

\hypertarget{data-journalism---a-quick-practical-guide-1}{%
\chapter{Data Journalism - A Quick \& Practical Guide}\label{data-journalism---a-quick-practical-guide-1}}

\hypertarget{Introduction_TOC}{%
\section{Outline - Introduction - Table of Contents}\label{Introduction_TOC}}

Each chapter would cover 5 to 10 pages. Much of the material will consist of original content I have prepared using open government datasets, such as the Arkansas Department of Health Covid-19 data or the FBI's crime statistics. I have been trained about the Fair Use issues and do not anticipate copyright issues.

Images will be screenshots I generate from my lessons. The chapters will include links to other web resources, such as the Tableau Public frequently asked questions. The chapters will include links to original video content I produced for my classes and that is hosted on video.uark.edu.

\hypertarget{table-of-contents}{%
\section{Table of Contents}\label{table-of-contents}}

\hypertarget{introduction-to-data-analysis}{%
\section{Introduction to data analysis}\label{introduction-to-data-analysis}}

--Introduction to data analysis, including math for journalists

\begin{verbatim}
Basics of Data Analysis
Numbers in the Newsroom
Excel Exercise: Transit Data and Calculating a Rate
Review: Mac OSX Basics
\end{verbatim}

--Organizing your workflow

\begin{verbatim}
Best practices in data management
Organizational tips for files
Data documentation skills
\end{verbatim}

--Data cleaning

\begin{verbatim}
Filtering
Reading Data Dictionaries
Data Cleaning Exercises
\end{verbatim}

--Data Visualization

\begin{verbatim}
Principles of Data Visualization
Cleveland McGill Scale
Important Resources for Surveying the Data Visualization Options
Color Choices
Build a Cover Image Using Canva or InDesign or Powerpoint
Higher Resolution Graphics in Tableau
\end{verbatim}

--Writing About Data

\begin{verbatim}
Writing Style Notes
Common Errors – Math
AP Style with Numbers
\end{verbatim}

--Excel Bootcamp

\begin{verbatim}
Review four corners
How to Filter in Excel
Basics and Sorting in Excel
Practice Rates and Ratios 
Excel formulas
Pivot Tables
Countif Function
\end{verbatim}

\hypertarget{section-2-data-analysis-tools}{%
\section{Section 2: Data Analysis Tools}\label{section-2-data-analysis-tools}}

--Basic Tableau

\begin{verbatim}
Downloading instructions for Tableau
Getting started tutorial with video
Building a basic COVID data chart with video and transcript
Using filters and calculations with video and transcript
Tutorial on Tableau calculations with video
Proper formatting of a filter bar in Tableau, video
Links to additional Tableau Tutorials
\end{verbatim}

--Tableau - Maps

\begin{verbatim}
Mapping tutorial & sample dataset
Build a Map COVID-19 Positivity in Arkansas Counties
Video
Dual Mapping - Bubble Maps
\end{verbatim}

--Basic Flourish

\begin{verbatim}
Videos to Get Started
Beginning Documents
Flourish Design Tips
More Resources
Adam Marton Cheat Sheet
Flourish newsrooms plan
Flourish - Stories
Examples from Fall Class
Basic Map
Flourish Links
\end{verbatim}

--Basic Datawrapper

\begin{verbatim}
  First Datawrapper Chart
  Tutorials
  Adam Marton Datawrapper Training
  Automatic chart updates
  Maps in Datawrapper
\end{verbatim}

\hypertarget{section-3-r-for-data-journalists}{%
\section{Section 3: R for data journalists}\label{section-3-r-for-data-journalists}}

--Introduction to R

\begin{verbatim}
  Install R and R Studio.
  Basic tutorial on R
  https://profrobwells.github.io/Guest_Lectures/Intro_To_R/R1_Intro-to-R.html
  Reading
  Reproducible research Repetitive tasks in modern newsrooms
  Popular R Libraries
  Data Types and R
  Reference: Logical Operators in R
  Packages
  Important Reference Materials
  R and R Studio CHECK REPETITION
\end{verbatim}

--R data visualization

\begin{verbatim}
  Basic GGPLOT
  Using color
  Formatting PNG for export
  Scatterplots
  Histograms
  Box plots
  Line graphs
  ggplot cookbook 4-26-20.rmd
\end{verbatim}

--R data cleaning

\begin{verbatim}
  Data cleaning exercises using SF police data  
  Clean names, Process dates  
  top_n: table with just the top five counties' crime rate  
  Grouping by Disposition   
  Filters   
  A more complex filter   
  String manipulation   
  Rename specific strings: str_replace_all   
  Using a lookup table to replace all the values   
  gsub - delete space   
  convert all text to lowercase   
  Make into html table   
  Make bubble chart   
  
\end{verbatim}

R Markdown to distribute findings to Stanford, Feb 2020
\url{https://profrobwells.github.io/HomelessSP2020/SF_311_Calls_UofA.html}
Homeless Children, Feb 25
\url{https://profrobwells.github.io/HomelessSP2020/Homeless_Children_Feb_25_2020.html}

--Cookbook of common tasks

\hypertarget{section-4-publishing-your-work}{%
\section{Section 4: Publishing your work}\label{section-4-publishing-your-work}}

--WordPress

\begin{verbatim}
  Using WordPress
  Access back end
  Embedding interactive data 
  Embed Flourish in WordPress
  Embed Tableau in WordPress
  Building the Web Page
\end{verbatim}

--GitHub for beginners

\hypertarget{appendix}{%
\section{Appendix}\label{appendix}}

--Teams and Slack

\hypertarget{notes}{%
\section{NOTES}\label{notes}}

Lectures
Investigative Reporters and Editors Inc., Society for Advancing Business Editing and Writing and similar national journalism organizations

\hypertarget{instructions-from-oer}{%
\subsection{Instructions from OER}\label{instructions-from-oer}}

project outline and project completion timeline. Please include examples or links to content you will use (if known), drafts of any completed chapters or other supporting documentation. Please also include anticipated needs for support from the OER team such as assistance searching for resources, instructional design support or assistance creating ancillary materials or graphics

You can label chapter and section titles using \texttt{\{\#label\}} after them, e.g., we can reference Chapter \ref{intro}. If you do not manually label them, there will be automatic labels anyway, e.g., Chapter \ref{methods}.

\hypertarget{introduction-to-data-analysis-1}{%
\chapter{Introduction to Data Analysis}\label{introduction-to-data-analysis-1}}

Sections in this Module

Basics of Data Analysis

Numbers in the Newsroom

Excel Exercise: Transit Data and Calculating a Rate

Review: Mac OSX Basics

Basics of Data Analysis

TransparencyReliability: How sure are we that we got the right answer? That we've done everything correctly?Replicability: If we had to do it all again, would we get the same answer? If someone else did it, would they?Transparency: If our results are challenged, can we show exactly what we've done to defend it?--Matt WaiteData Analysis

--- Review methodology with one or more other data people--- Check results to other available comparable data--- Ensure all record counts are consistent across stages--- Check averages --- Examine outputs to ensure logical consistency (do things that should add up to 100\% add up to 100\%?)--- Recheck all coding line by line if possible or in aggregate if not --- Re-read all programs/scripts--- Re-run entire analysis from scratch--- Check each number against analysis or source material prior to publication--- Recheck each number against analysis or source material on each draft Credit: Daniel Lathrop. Dallas Morning News

AP Stylebook Entry on Data Journalism

Data sources used in stories should be vetted for integrity and validity. When evaluating a data set, consider the following questions:--What is the original source for the data? How reliable is it? Can we get answers to questions about it?-- Is this the most current version of the data set? How often is the data updated? How many years of data have been collected?--Why was the data collected? Was it for purposes of advocacy? Might that affect the data's reliability or completeness? Does the data make intuitive sense? Are there anomalies (outliers, blank values, different types of data in the same field) that would invalidate the analysis?--What rules and regulations affect the gathering (and interpretation) of the data?--Is there an alternative source for comparison? Does the data for a parallel industry, organization or region look similar? If not, what could explain the discrepancy?--Is there a data dictionary or record layout document for the data set? This document would describe the fields, the types of data they contain and details such as the meaning of codes in the data and how missing data is indicated. If the data collectors used a data entry form, is the form available to review? For example, if the data entry was performed by inspectors, is it possible to see the form they used to collect the data and any directions they received about how to enter the data?Data and the results of analysis must be represented accurately in stories and visualizations. Any limitations of the data must also be conveyed. If one point in the analysis is drawn from a subset of the data or a different data set altogether, explain why this was done.Use statistics that include a meaningful base for comparison (per capita, per dollar). Data should reflect the appropriate population for the topic: for example, use voting-age population as a base for stories on demographic voting patterns. Avoid percentage and percent change comparisons from a small base. Rankings should include raw numbers to provide a sense of relative importance.When comparing dollar amounts across time, be sure to adjust for inflation. When using averages (that is, adding together a group of numbers and dividing the sum by the quantity of numbers in the group), be wary of extreme, outlier values that may unfairly skew the result. It may be better to use the median (the middle number among all the numbers being considered) if there is a large difference between the average (mean) and the median.Correlations should not be treated as a causal relationship. Where possible, control for outside factors that may be affecting both variables in the correlation. Use round numbers where possible, particularly to avoid a false appearance of precision. Be clear about limitations of sample size in reporting on data sets. See the polls and surveys section for more specific guidance on margin of error.Try not to include too many numbers in a single sentence or paragraph.

A refresher on~AP Stylebook on numbers

How to Lie With Statisticshttps://www.datasciencecentral.com/profiles/blogs/how-to-lie-with-visualizations-statistics-causation-vs

Sheffo, Catherine. ``How to Avoid 10 Common Mistakes in Data Reporting.''~American Press Institute~(blog), August 9, 2016.~https://www.americanpressinstitute.org/publications/data-reporting-common-mistakes/

Writing Assignment

~Numbers in the Newsroom

Sarah Cohen, Math Diva

Sarah Cohen's ``Numbers in the Newsroom'' is a classic in journalism numeracy. She is a Pulitzer-winning journalist at The Washington Post, a former Duke University professor, a data journalist at The New York Times., now a professor at Arizona State University. That's why we read her book.

\begin{itemize}
\tightlist
\item
  Limit yourself to 8-~12 digits, including dates such as 2012, in a single paragraph.--This allows us to stress the most important numbers
\end{itemize}

--Simplify your story using rates, ratios or percentages. ``One in four'' = ratio or rate. ``Forty percent'' = ratio or rate. 235 deaths per 100,000 is another. See pg. 11

*Memorize some common numbers on your beat:~Population of Fayetteville. Population of Arkansas. Population of the U.S. Per capita income Arkansas and U.S.

\emph{Round off!~Unless you're dealing with really small numbers, decimal points may not be meaningful. ``I'm a big fan of rounding,'' Cohen said.} To make a very small number more understandable, divide it into 1. For example, .0081 is the proportion of the U.S. population who die every year. 1/.0081 translates to 1 in every 124 Americans die each year.* If you have a story filled with numbers -- and not people --- it needs to be really, really short.

\begin{itemize}
\tightlist
\item
  Portion of whole -- For example, at the time of the Million Man March in 1995, a turnout of 1 million black men would have represented 1/12th of all the black men in the country at the time.
\end{itemize}

Rates and Ratios

Numbers in the Newsroom: Rates and Ratios

Class exercise: Cohen: Think in ratios -- construct a ratio on the poverty beat. Memorize common numbers on the beat:

Use the Census Poverty \url{Data:\%C2\%A0};US Ark Counties Poverty ACS\_16\_5YR\_DP03\_with\_ann-1w6iwss

--In the spirit of ``memorizing numbers on your beat,'' find three statistics about poverty in this dataset

--Construct a rate or ratio about the number of households earning~\$15,000 to \$24,999 for the U.S., Arkansas, and the counties with the highest and lowest percentages in this category. Remember -- ``percents are Fractions. Fractions are percents''

Excel Exercise: Transit Data and Calculating a Rate

Basic Excel: http://www.interhacktives.com/2015/11/02/quick-tips-excel-google-sheets/

This exercise involves calculating train rate fatalities.Click here for the instructions:Exercise4Click here for the data:transitNotes:--Create data dictionary, backup, do four corners test--Be very careful about copying different block of data to a new sheet: mixups--Copy labels over and then delete them just to be sure all is aligned--Class walkthrough with 2008 - 2009 derailments--Be very specific about the headers: Total Derailments 2009,~Vehicle Revenue Miles--Word Wrap for headers--We are constructing two derail rates, one in 2009 and another in 2008.--Results are 0? Wait, check the decimal tool--Results to two decimals. Rarely more than that--Copy of acronym definitions to data dictionaryExercise \#1:--Calculate derailment rates for 2008-2013, determine the average rate, which agency had the highest average rate?Exercise \#2:--Calculate the rate of fatalities (excluding suicides) by total miles (vehicle revenue miles)--Copy all of the Total Heavy Rail Fatality Sum, excluding suicides and all of the~Vehicle Revenue Miles (VRM)--Create rates for each year, then average them Which city has the highest rate of fatalities (excluding suicides) over the last six years and where does Chicago rank? Exercise \#3:Over the six years, did Chicago transit have more derailments than other major city transit systems? Is it getting better or worse? Which year was the worst for all major transit in terms of fatalities (excluding suicides)? How many suicides happened at CTA in 2013? What questions should I ask the DOT data clerks regarding the data? What other data might be useful to mine after this story runs?Resources: Excel Formulas in NICAR Coursepack

transit

Relative Risk

``Black applicants are denied mortgages at twice the rate of whites with similar incomes.''

If 20 smokers per thousand contract cancer, and yet non-smokers have a cancer rate of only 10 per thousand, the relative risk of smoking is 2.

``More than'' or ``less than'' = compute difference between the smokers, an extra step

Example: ~Relative RiskFiguring Rates -- Numbers in NewsroomMathCrib-Doig

Excel Exercises

Click here for: Basics and Sorting in ExcelClick here for: CityBudget.xls

Click here for the data: UrbanPopClick here for assignment: Exercise \#1~Answer these questions:Sorting--Which urban agglomeration was the largest in 1950?--Which is expected to be the largest in 2030?~Percentage ChangeFormula: (New number-Old Number)/Old Number * 100 and use \% symbolCreate columnWhat is difference.---copy forumulaWhat is percentage change---copy formula~Percentage Change--Which had greatest rate of change between 1950-2015?--Are any urban areas expected to lose population from 2010 to 2030?--If so, how many and which one is expected to lose the most?--Which United States urban area is expected to have the largest percent increase from 2015 to 2030?

Refresher on Mac OSX operating systemHere is a short video course that you can skim through and get up to speed on how to use the Apple operating system, OSX.https://www.linkedin.com/learning/macos-mojave-essential-training/understand-macos-the-foundation-of-working-with-a-mac?u=50849081I would hammer through the following as soon as possible.Chs. 1, 3 are~importantChapter 2: Finder will be crucial.Ch. 5 on downloading from the web is importantCh. 4, 13 should be skimmedChs~6-11 aren't important for our class

\hypertarget{organize-your-data}{%
\chapter{Organize Your Data}\label{organize-your-data}}

This module addresses:--Best practices in data management--Organizational tips for files--Data documentation skills

Staying organized is a key problem for beginning data students.You can't find files. You have duplicate files and struggle to find the latest version.Your data software fails because it can't find your files.You can't remember where you got the source data or what the headers mean.You waste hours with this stuff when you really should be reporting.

I want to put an end to this nightmare. These organizational tools below are essential.

Storage

Organize Your Data: Finder

Finder, not always up for the job

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Sort by grid, by date.--This allows you to see the latest version of your files.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Path name.--Follow this convention: Description of File With Some Detail, Date. If you are editing something, put your initials at the end.--i.e.: Covid\_Master\_File\_Jan\_11\_2021-rsw
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Copying File Paths from the Mac Finder.Navigate to the file or folder you wish to copy.Right-click (or Control+Click, or a Two-Finger click on trackpads) on the file or folder in the Mac Finder While in the right-click menu, hold down the OPTION key to reveal the ``Copy (item name) as Pathname'' option, it replaces the standard Copy optionOnce selected, the file or folders path is now in the clipboard, ready to be pasted anywhere
\end{enumerate}

Data Diary

Data Dictionary

Data Diary ExamplesThe following material was posted on NICAR-L, a listserv for data journalists. There are some great examples of how the pros use data diaries / data dictionaries in their workflow.1) GeoffThis is a great question, and I'm finding as I think through my response that it's helpful to remind myself of good practices.I use Jupyter notebooks for when I'm doing analysis or exploration in Python or SQL and R Markdown for when I'm doing it in R. However, I would stress that any data diary you keep and keep in a detailed way that is useful to you and others later, regardless of format, is better than the one you don't.https://github.com/newsapps/public-notebooks/blob/master/Shooting\%20victims\%20by\%20block.ipynb~is an example of a representative but not great notebook for a small data task.A few things that I try (but don't always succeed) to do:-- Link to the source data, summary reports and codebooks near the top of my notebook. This is both a convenience to me, because I refer to these often, and especially to others who may not have seen those things before.-- Put a high level summary of why I'm interested in the data and what I'm trying to find at the top of the notebook. This keeps me focused as I'm doing my exploration and also is helpful for others who might be skimming.-- Keep a parking lot of questions (or potential concerns about validity or cleanliness of data) near the top of the notebook. That way I can quickly capture things I think about as I'm exploring or analyzing the data, while still staying focused.-- Near the end of my day (or the first thing the next morning), do a quick pass over a notebook I worked on during the day. Do my notes still make sense? Are they as clear as they could be? If not, try to clean them up.~ If I don't have time at the moment, I at least leave a ``TODO'' note to flag the section as needing some love.-- Share the notebook with someone else as early as possible, even if you're still in-progress. This is the most helpful way to know if I'm capturing your process with enough granularity. Or maybe I'm getting too granular. If so, is there a way to summarize~ process and findings at the top of a section?-- If using code, don't give a play-by-play of the code in text. Instead, describe what I'm trying to find out, why it's important and why I'm taking a particular approach. Also note any assumptions my code is making.Hopefully this is helpful.Best,Geoff2) Christian McDonaldOh, do I have feelings about this one\ldots{}I keep a data diary for myself that has everything from notes about public information requests, notes about where I got data, descriptions of what I did, sql queries and all kinds of things. I sometimes also make a data report that is really RESULTS of what I learned, as opposed to how I got there in the data diary. The data report is more for other reporters, editors and maybe sources, but the diary is for me, so less formal.These days I'm trying to script more of my work using Jupyter Notebooks, which then tends to be a mix of the two. It has info about where the data came from and the code that made the result. Sometimes it is written for future me, sometimes for the public. Generally, I'll still keep a personal data diary just for my future self, `cause I can't remember what I did yesterday much less last week.Data diaries I tend to write in markdown files on my machine so code doesn't get wigged with curly-quote translations. Data reports are typically Google Docs or Jupyter Notebooks on Github.

\hypertarget{data-cleaning}{%
\chapter{Data Cleaning}\label{data-cleaning}}

Basic Population - Race Census Data Download Instructions

Census: data.census.gov

https://data.census.gov

1) Advanced Search--Topics \textbar{} Geography \textbar{} Years \textbar{} Surveys \textbar{} Codes2) Topics \textbar{} Race and Ethnicity \textbar{} White--Note that the ``White'' filter displays below3) Geography \textbar{} County \textbar{} Arkansas \textbar{} All Counties in Arkansas--Note that the ``All counties in Arkansas'' filter displays4) Search!5) Select Table Named RACEAmerican Community SurveyTotal PopulationTableID: B020016) Switch to 2016: ACS 5-Year Estimates Detailed Tables7) Customize Table. Download. Make Sure to Download~2016: ACS 5-Year Estimates Detailed Tables

Clean Census Data1) Create Data Dictionary2) Duplicate Sheet3) Four corners select and copy4) New Sheet. Paste Special \textbar{} Transpose--the races are now the rows--Filter by Estimate: Contains Estimate, Delete5) Edit Headers: White, Black, Hispanic6) Check totals - do they add up?7) Two races including Some other race. Two races excluding Some other race, and three or more races (delete)8) Save and Load to Tableau9) Build a Arkansas Population Map by Race

Income by Race

https://data.census.govAdvanced SearchFilters \textbar{} GeographyCounties \textbar{} Arkansas \textbar{} All countiesFilters \textbar{} Topics \textbar{} Income and PovertyFilters \textbar{} Topics \textbar{} Race and EthnicityFilters \textbar{} Years \textbar{} 2016Filters \textbar{} Text Search in Find a Filter: ``Income'' \textbar{} Select "Income (Households, Families, Individuals)Search

Download White Only, Black Only, Hispanic or Latino HouseholderYour tables will say this:HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2016 INFLATION-ADJUSTED DOLLARS) (WHITE ALONE HOUSEHOLDER) Survey/Program: American Community Survey Product: 2016: ACS 1-Year Estimates Detailed Tables

 Tables: B19001A, B19001B, B19001I~Download - select .csv

TableauClean Data as described in previous lessonCombine the three tables in Tableau linking to the income as a common field.Create a chart

PAST TUTORIALS IN AMERICAN FACT FINDER.

NEED TO REVISE

https://factfinder.census.gov/faces/nav/jsf/pages/index.xhtml

Household income data for counties and state and national. Gender and demographics of low-wage workersAmerican FactFinderhttps://factfinder.census.gov/faces/nav/jsf/pages/index.xhtmlAdvanced Search \textbar{} Show Me AllTopics \textbar{} People \textbar{} PovertyGeographies \textbar{} County \textbar{} Arkansas \textbar{} All Counties Within ArkansasSelect Table S1701, Poverty Status in the Past 12 MonthsModify Table---Select top Filter---Total and Percent Below Poverty Level---Select second Filter---Keep Estimate, do not check margin of ErrorDownload

30:00 shows how to use the fact finderhttps://www.census.gov/data/training-workshops/recorded-webinars/measuring-america.html

Selected Economic Characteristics DP03 2012-2016 American Community Survey 5-Year Estimates

Standard Data Cleaning

Data is: ACS\_16\_5YR\_DP03 DP03 SELECTED ECONOMIC CHARACTERISTICS~ ~2012-2016 American Community Survey 5-Year EstimatesCopy main data sheet and call copy wages below \$25kDelete all data fields except headers and these columnsHC01\_VC74 Estimate; INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS) -- Total householdsHC01\_VC75 Estimate; INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS) -- Total households -- Less than \$10,000 HC03\_VC75 Percent; INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS) -- Total households -- Less than \$10,000 HC01\_VC76 Estimate; INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS) -- Total households -- \$10,000 to \$14,999 HC03\_VC76 Percent; INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS) -- Total households -- \$10,000 to \$14,999 HC01\_VC77 Estimate; INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS) -- Total households -- \$15,000 to \$24,999 HC03\_VC77 Percent; INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS) -- Total households -- \$15,000 to \$24,999 HC01\_VC85 Estimate; INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS) -- Total households -- Median household income (dollars)--Rotate header rows, wrap text.Shrink verbiage from~Estimate; INCOME AND BENEFITS (IN 2016 INFLATION-ADJUSTED DOLLARS) -- Total households to ``Total households''Total households \%Total households Total households -- \textgreater{}\$10k \%Total households -- \textgreater{}\$10k Total households -- \$10kto \$14,999 \%Total households -- \$10kto \$14,999 Total households -- \$15,000 to \$24,999 \%Total households -- \$15,000 to \(24,999 Median household income\)--Specify Arkansas-stateThen find/replace to eliminate ``County, Arkansas'' from geography labels.Create Total Under \$25 column.Add Total households -- \textgreater{}\$10k + Total households -- \$10k to \$14,999 + Total households -- \$15,000 to \$24,999Create \% Under \$25k column (total Under \$25k / total households)Copy formulas downCheck mathWhen satisfied, copy and paste valuesMore on Data Cleaning Census spreadsheets~--Download the view and the data versions of large spreadsheets. One to guide you. the other to do the work.--Merge / unmerge cells--Find-Replace--- =CONCATENATE(B3, B4).

Census~Demographic data

Household income data for counties and state and national. Gender and demographics of low-wage workersAmerican FactFinderhttps://factfinder.census.gov/faces/nav/jsf/pages/index.xhtmlAdvanced Search \textbar{} Show Me AllTopics \textbar{} People \textbar{} Poverty \textbar{} Poverty (added to Your Selections)Geographies \textbar{} County \textbar{} Arkansas \textbar{} All Counties Within ArkansasGeographies \textbar{} United StatesGeographies \textbar{} ArkansasSelect Table S1701, Poverty Status in the Past 12 MonthsModify Table---Select top Filter---Total and Percent Below Poverty Level---Select second Filter---Keep Estimate, do not check margin of ErrorDownload---Use the DataDownload Again---View the Data---Excel spreadsheetQuestions about categories and definitions:See ``Table Notes'' to far right on factfinder website after you've generated a table.https://www2.census.gov/programs-surveys/acs/tech\_docs/subject\_definitions/2016\_ACSSubjectDefinitions.pdfRead: ``Poverty Status in the Past 12 Months''``Poverty Status of Households''Definitions. working Poor--Poverty thresholds:The actual poverty thresholds vary with the makeup of the family. In 2015, the weighted average poverty threshold for a family of four was \$24,257; for a family of nine or more people, the threshold was \$49,177; and for one person (see Unrelated individuals), it was \$12,082. Poverty thresholds are updated each year to reflect changes in the Consumer Price Index for All Urban Consumers (CPI-U). Thresholds do not vary geographically. (For more information, see ``Income and poverty in the United States: 2015.'')\url{https://www.bls.gov/opub/reports/working-poor/2015/home.htm\#unrelatedindividual}Weighted Average PovertyThresholds in 2015 by Size ofFamily(Dollars)One person 12,082Two people 15,391Three people 18,871Four people 24,257Five people 28,741Six people 32,542Seven people 36,998Eight people 41,029Nine people or more 49,177Source: U.S. Census Bureau.https://www.census.gov/content/dam/Census/library/publications/2016/demo/p60-256.pdfhttps://www.census.gov/data/tables/time-series/demo/income-poverty/historical-poverty-thresholds.html

--Download the view and the data versions of large spreadsheets. One to guide you. the other to do the work.

--Merge / unmerge cells

--Find-Replace

--- =CONCATENATE(B3, B4).

Cleaned and download 2011-2015 estimates with detailed poverty metricsArk Counties full income search 5-10-17 ACS\_15\_5YR\_DP03

Students assigned geographical location for Census data.

Questions:

--Number and Percentage of Minimum Wage Households?

--Compare to National, State Averages

--Produce basic Tableau chart

\hypertarget{data-visualization}{%
\chapter{Data Visualization}\label{data-visualization}}

Principles of Data Visualization``Our limited brains are incapable of grasping reality in all its glorious complexity.''What you design is never exactly what your audience ends up interpreting so reducing the chances for misinterpretation becomes crucial. Cleveland McGill Scale

Cleveland McGill Scale for Data Visualization

\url{https://www.youtube.com/watch?v=XGPkdOczRtk\&feature=youtu.be}

Important Resources for Surveying the Data Visualization Options Dataviz Catalog http://www.datavizcatalogue.com/ FT Visual Vocabulary https://github.com/ft-interactive/chart-doctor/blob/master/visual-vocabulary/Visual-vocabulary.pdf For the weekly memo: Select two examples from the Dataviz Catalog and FT Visual Vocabulary that you find interesting or useful. Include a screenshot of the chart in your memo and describe how it could apply for our project.

Graphics Comments from Jon Schleuss, Los Angeles TimesAnd the colors. What does ``red'' mean when it's used? And what about using too many colors. At the Times we really only have two or three colors: basic default, a highlight color and a negative color. We break from convention, but keeping it simple helps. I figure now I'll show them how I approach chart building from start to finish.Also, I see a desire to combine different data into the same chart. So there's a left, bottom and right axis.~But that's a bit confusing to the reader,~especially when things have the same values (percentages vs.~percentages instead of percentages vs.~hard counts).I think my big takeaways are that most of these charts should be flipped on their sides. That's because when we sort data largest to smallest (nearly everyone did) we then think of it as time passing if it's a column chart (bars situated left to right). And that there's a downward marching trend. Best to flip a lot of these on their side. Build choropleth maps

A Comment on Color Choices A reader made an excellent point that the red shading of the active cases map was misleading since `red zone' is a specific concept in the White House task force reports. Our shading does not match the red zone definition of the task force report and most readers would expect that it would. I swapped out the shading for blue-green until we figure out the calculations for active cases per capita on that White House task force scale. It just goes to show you how color choices on graphics are major communication issues. Reader Comment: \citet{BruceWard2} Have you considered using a standard for which counties are red?~ The map gives a false impression that Arkansas counties are not ``red zones'' for CoVID when they are. Replying to \citet{BruceWard2} and \citet{KatySeiter<br}\textgreater{}

Build a Cover Image Using Canva or InDesign or Powerpoint https://www.canva.com/ ~

Rachell Sanchez-Smith used Canva for a simple animation.

Higher Resolution Graphics in Tableau https://www.dataplusscience.com/HighResolution.html Higher Resolution Photos: at least 72 DPI. Practically, should be higher. --500k or more is a safe bet --Cropping reduces file size. Grainy Guidance: https://cft.vanderbilt.edu/wp-content/uploads/sites/59/Image\_resolutions.pdf Higher Resolution Graphics in Tableau https://www.dataplusscience.com/HighResolution.html ~ ~

\hypertarget{writing-about-data}{%
\chapter{Writing About Data}\label{writing-about-data}}

Writing Style Notes~Writing style notesDon't use this ``respectively'' construction.~It confuses the readers and leads to data errors.Other private trade schools also made the top 10 list, such as Philander Smith in Little Rock and Bryan University in Rogers, with increases of 81 percent and 74 percent respectively.~.ITT Technical Institute, the University of phoenix, Philander Smith College and Bryan University are all classified as private schools and are the top four schools with graduated student loan debt in the state. Their debt has increased 106 percent, 102 percent, 81 percent and 74 percent respectively since 2012.

AP Style with Numbers

AP Numerals EntryDownload

\hypertarget{excel-bootcamp}{%
\chapter{Excel Bootcamp}\label{excel-bootcamp}}

PIVOT TABLES

Basic introduction to pivot tables

Calculations and Pivot Tables

~

COUNTIF Function for Tabulating Text

\url{https://youtu.be/5NdImlnWmsI}

\hypertarget{basic-tableau}{%
\chapter{Basic Tableau}\label{basic-tableau}}

This module addresses:--Downloading instructions for Tableau--Getting started tutorial with video--Building a basic COVID data chart with video and transcript--Using filters and calculations with video and transcript--Tutorial on Tableau calculations with video--Proper formatting of a filter bar in Tableau, videoLinks to additional Tableau Tutorials

Dashboards and Embedding Tableau Public in WordPress

Maps in Tableau

Tableau Download and License

Introduction to Tableau

Build Your First Tableau Chart - Deaths by Counties

This chart was filtered to show counties with deaths 25 and greater

Formatting a Graphic

Filters and Calculations

More on Tableau, Basic Excel Skills: FBI Data

Tableau Calculations

How to Tweak A Filter to Display Properly

Additional Tableau Tutorials

Dashboards and Embedding Tableau Public in WordPress

Maps in Tableau -

Dual Axis

MATERIAL ON THIS PAGE USES NON-COVID DATA EXAMPLES

Histogram

This is a detailed walk-through of how to add a cumulative distribution to a histogram in Tableau.~ ~Build a histogram with \% Female Households in PovertyEasiest method: click on\% Female Households in Poverty and choose the histogram from Show MeFind out where this is happening: drag Geography to the pane. Now hover your mouse over the blocks and you will see the counties.~Duplicate the CNT(Profit) pill on Rows by Ctrl+drag the pill next to itself on the Rows shelfThis gives you a new marks card -- now you can create 2 different types of mark for a single data field. On the new marks card ``CNT(Profit)(2)'', change the mark type to a lineChange the color as well, if desiredRight click on the duplicated field on the Rows shelf and make it a dual axisApply a Quick Table Calculation of Running Total to the duplicated field{[}{[}If students find this histogram to be uninteresting, add a filter on Profit to ignore outliers (maybe go from -500 to +500). Then right-click Profit(bin) dimension and Edit to make the bin size smaller, maybe 25.{]}{]}Create a Reference Line for PovertyStep 1 -- Build the ViewDrag \% Female Households -- Children 5 Years to the~Rows~shelf.Drag Geography to the~Columns~shelf.Step 2 -- Create ParametersRight-click in the~Data~pane and then select~Create Parameter.Name the parameter ``Arkansas Average''.Under~Data Type~select~Integer.Under~Current Value, set to 55.8Under~Allowable values~select~All.Click~OK.Step 3: Create the calculated fieldSelect~Analysis~\textgreater{}~Create Calculated Field.Name the calculated field~``Reference Line''.In the formula field, enter the following formula:IF{[}\% Female Households -- Children 5 years younger{]}={[}Arkansas Average{]} THEN {[}Arkansas Average{]} ENDClick~OK.Step 4 -- Use the calculated field as a Parameter ControlDrag the ``Reference Line ``calculated field to~Details. This is the box below Color in the Marks CardClick the arrow to change the measure from SUM to~Minimum.In the view, right-click on the Y axis and select~Add Reference Line.In the~Value~drop down menu, select~Minimum(Reference Line).In the~Label~drop-down menu, select~Value.Click~OK.Visualize the income distribution in a histogram\% of Female Households -- Children 5 Years and Younger.--Drag to Columns--Show me: Select Histogram--Distribution of the poverty level.

Bins and GroupsCreate Bins:~https://onlinehelp.tableau.com/current/pro/desktop/en-us/calculations\_bins.htmOther options besides bins:~Use parameters to organize \url{data:\%C2\%A0};https://onlinehelp.tableau.com/current/pro/desktop/en-us/parameters\_create.htm~Use sets to organize \url{data:\%C2\%A0};https://onlinehelp.tableau.com/current/pro/desktop/en-us/sortgroup\_sets\_create.htm\#UseCreate Bins:~\url{https://onlinehelp.tableau.com/current/pro/desktop/en-us/calculations_bins.htm}Format Filters -- See video belowUse parameters to organize \url{data:\%C2\%A0https://onlinehelp.tableau.com/current/pro/desktop/en-us/parameters_create.htm}Use sets to organize \url{data:\%C2\%A0https://onlinehelp.tableau.com/current/pro/desktop/en-us/sortgroup_sets_create.htm\#Use}

\#\#Need to Edit below, may duplicate the earlier section
\textbf{Track \#1: Tableau}

\textbf{Arkansascovid.com Data}

\hypertarget{flourish}{%
\chapter{Flourish}\label{flourish}}

Flourish

\hypertarget{wordpress}{%
\chapter{WordPress}\label{wordpress}}

Looks like this:

Building the Web PageGutenberg has blocks to display text, graphics, video etc.Everyone has to build their own page in DataReporting site of WordPress.Tasks:Create a Post.Upload your graphic from Assignment \#1 and your story. Format so it doesn't look uglyClick ``Student Work'' for category.

\hypertarget{datawrapper}{%
\chapter{Datawrapper}\label{datawrapper}}

\hypertarget{r-introduction}{%
\chapter{R Introduction}\label{r-introduction}}

Beginner's guide to R: Introduction

https://www.computerworld.com/article/2497143/business-intelligence/business-intelligence-beginner-s-guide-to-r-introduction.html

RStudio IDE Easy Tricks You Might've Missed

https://rviews.rstudio.com/2016/11/11/easy-tricks-you-mightve-missed/

How Do I?

https://smach.github.io/R4JournalismBook/HowDoI.html

Packages

https://smach.github.io/R4JournalismBook/packages.html

~Download R and RStudio

http://www.machlis.com/R4Journalists/download-r-and-rstudio.html

You can download the most recent version of R at~https://www.r-project.org/, which is the home of R (formally known as the R Project for Statistical Computing). The R-project home page usually includes information about the latest versions of R. Don't be put off by the sometimes odd nicknames for R versions, such as ``Very, Very Secure Dishes'' and ``Bug in Your Hair'' -- the software is much more useful than you might assume from the nicknames. (The whimsical version names come from various Peanuts cartoons.)

There should also be a prominent link to download R. Click that download option and you should be taken to CRAN, the Comprehensive R Archive Network, and a list of CRAN servers, called mirrors, around the world. Pick a server and choose the~precompiled binary distribution~for your operating system. Once the file finishes downloading, install it like any other software program - run the .exe for Windows or .pkg for Mac.

You should be fine accepting all the Mac defaults. On Windows, you'll need to decide whether you want the 32- or 64-bit R version. (Unless you've got a pretty old system, chances are you'll want 64-bit.)

This is all you need to start running R, but I strongly recommend also installing RStudio, a free platform designed to make it easier and more enjoyable to create and run R code. Head to~RStudio.com~and under products, look for RStudio and then RStudio~Desktop~(not Server), and download the free Open Source Edition version for your operating system. This, too, installs like a typical software program

R NOTES THAT NEED TO BE CLEANED UP

Today's set of tasks:

March 29 class-2lrqupg

Data

US Ark Counties Poverty ACS\_16\_5YR\_DP03-Jan 24-y46vv7

Race Poverty Set

ACS\_16\_5YR\_S1701\_with\_ann-28nvp6q

File Header Definitions

ACS\_16\_5YR\_S1701\_metadata-1on99rr

R4JournalismBook

https://github.com/smach/R4JournalismBook

https://smach.github.io/R4JournalismBook/booklinks.html

Functions

https://smach.github.io/R4JournalismBook/functions.html

{[}et\_pb\_section bb\_built=``1''{]}{[}et\_pb\_row{]}{[}et\_pb\_column type=``4\_4''{]}{[}et\_pb\_text admin\_label=``Key Resources for R'' \_builder\_version=``3.17.2''{]}

You will be using these materials

a lot during the course of the semester.

Machlis, Sharon. Practical R for Mass Communication and Journalism. Chapman \& Hall/CRC, 2018. \url{http://www.machlis.com/R4Journalists/}.

RStudio IDE Easy Tricks You Might've Missed
\url{https://rviews.rstudio.com/2016/11/11/easy-tricks-you-mightve-missed/}

How Do I?
\url{https://smach.github.io/R4JournalismBook/HowDoI.html}

Functions:~
\url{https://smach.github.io/R4JournalismBook/functions.html}

Packages:
\url{https://smach.github.io/R4JournalismBook/packages.html}

~

{[}/et\_pb\_text{]}{[}/et\_pb\_column{]}{[}/et\_pb\_row{]}{[}/et\_pb\_section{]}

\textbf{R and R Studio}

\begin{verbatim}
Install R and R Studio.

This is free and open source software. It is not large and doesn't tax the memory a lot. 
R runs on Windows, Mac and Linux, but this course is designed for the Mac version. 
If you use Windows, there may be variations in the lessons and instructions. Please see me      for questions.

Installing R is a two-step process: 
1) Install R, the actual program
2) Install RStudio, a common interface 

1) Download the most recent version of R for Mac:         
\end{verbatim}

\url{https://mirrors.nics.utk.edu/cran/bin/macosx/R-4.0.2.pkg}

\begin{verbatim}
--If you have a Windows computer, go to: 
\end{verbatim}

\url{https://mirrors.nics.utk.edu/cran/bin/windows/base/R-4.0.2-win.exe}

\begin{verbatim}
Accept all of the default settings for Mac.

 2) Install RStudio, the interface we use to manage and create R code. Download the open         source edition of R Studio desktop and follow the prompts to install it.   
\end{verbatim}

\url{https://rstudio.com/products/rstudio/download/\#download}

\begin{verbatim}
 Good instructions for installing R
\end{verbatim}

\url{http://www.machlis.com/R4Journalists/download-r-and-rstudio.html}

\begin{verbatim}
Good overview of the program
\end{verbatim}

\url{https://docs.google.com/presentation/d/1O0eFLypJLP-PAC63Ghq2QURAnhFo6Dxc7nGt4y_l90s/edit\#slide=id.p}

\hypertarget{r-data-viz}{%
\chapter{R Data Viz}\label{r-data-viz}}

\hypertarget{part-6-chart-by-gender}{%
\chapter{Part 6: Chart By Gender}\label{part-6-chart-by-gender}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MediaBucks <-}\StringTok{ }\NormalTok{rio}\OperatorTok{::}\KeywordTok{import}\NormalTok{(}\StringTok{"https://github.com/profrobwells/Guest_Lectures/blob/master/Intro_To_R/RealMediaSalariesCleaned.xlsx?raw=true"}\NormalTok{, }\DataTypeTok{which =} \StringTok{"RealMediaSalaries2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MediaBucks }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ Salary, }\DataTypeTok{x=}\NormalTok{Gender)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Total Media Salaries by Gender"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"Source: RealMediaSalaries survey, 2019 "}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Rob Wells"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"County"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Salary"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 4 rows containing missing values (position_stack).
\end{verbatim}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-3-1.pdf}
This needs some work

\begin{itemize}
\tightlist
\item
  \textbf{Get rid of scientific notation}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{options}\NormalTok{(}\StringTok{"scipen"}\NormalTok{=}\DecValTok{100}\NormalTok{, }\StringTok{"digits"}\NormalTok{=}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MediaBucks }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ Salary, }\DataTypeTok{x=}\NormalTok{Gender)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{   }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels =}\NormalTok{ scales}\OperatorTok{::}\NormalTok{dollar) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Total Media Salaries by Gender"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"Source: RealMediaSalaries survey, 2019 "}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Rob Wells"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"County"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Salary"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 4 rows containing missing values (position_stack).
\end{verbatim}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{itemize}
\tightlist
\item
  \textbf{Add Color}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MediaBucks }\OperatorTok{%>%}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ Salary, }\DataTypeTok{x=}\NormalTok{Gender, }\DataTypeTok{color =}\NormalTok{ Gender)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\CommentTok{#coord_flip() +     #this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels =}\NormalTok{ scales}\OperatorTok{::}\NormalTok{dollar) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Total Media Salaries by Gender"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"Source: RealMediaSalaries survey, 2019 "}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Rob Wells"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"County"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Salary"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 4 rows containing missing values (position_stack).
\end{verbatim}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{itemize}
\tightlist
\item
  \textbf{Average salaries is the story!}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MediaBucks }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(Gender, Salary) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Gender) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarize}\NormalTok{(}\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(Salary, }\DataTypeTok{na.rm=}\OtherTok{TRUE}\NormalTok{))  }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y =}\NormalTok{ mean, }\DataTypeTok{x=}\NormalTok{Gender, }\DataTypeTok{color =}\NormalTok{ Gender, }\DataTypeTok{fill=}\NormalTok{Gender)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position =} \StringTok{"none"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{labels =}\NormalTok{ scales}\OperatorTok{::}\NormalTok{dollar) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Average Media Salaries by Gender"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"Source: RealMediaSalaries survey, 2019 "}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Rob Wells"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"County"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Salary"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-7-1.pdf}

\begin{itemize}
\tightlist
\item
  \textbf{Export: Lower right, Export as .png file}
\end{itemize}

\#Machlis - Basic Data Visualization
\#Wickham - MPG charts
\#Updated Feb 4 2019

\#load software - Select NO when asked to restart
install.packages(``ggplot2'')
install.packages(``dplyr'')
install.packages(``usethis'')
install.packages(``forcats'')

\#call software into memory
library(ggplot2)
library(dplyr)
library(usethis)
library(forcats)

\#Basic demo
\#You will run the commands from the Console below
demo(topic=``graphics'')

library(dplyr)

\#Tutorial
\#Import Data, Create Dataframe, Rename Columns
snowdata \textless{}- rio::import(``data/BostonChicagoNYCSnowfalls.csv'')
bostonsnow \textless{}- select(snowdata, Winter, Boston)
names(bostonsnow){[}2{]} \textless{}- ``TotalSnow''

\#Doing the same thing but with pipe function
bostonsnow2 \textless{}- select(snowdata, Winter, Boston) \%\textgreater{}\%
rename(TotalSnow = Boston)

\#Doing the same thing but more efficiently
bostonsnow3 \textless{}- select(snowdata, Winter, TotalSnow = Boston)

\#Basic graphs
plot(bostonsnow\$TotalSnow)

hist(bostonsnow\(TotalSnow) boxplot(bostonsnow\)TotalSnow)
barplot(bostonsnow\(TotalSnow) barplot(sort(bostonsnow\)TotalSnow, decreasing = TRUE))

\#qplot
qplot(data=bostonsnow, y = TotalSnow)
qplot(y = bostonsnow\$TotalSnow)

\#basic ggplot2 - boxplot
ggplot(data=snowdata) +
geom\_boxplot(aes(x = ``Boston'', y = Boston))

\#dual box plots
ggplot(data=snowdata) +
geom\_boxplot(aes(x = ``Boston'', y = Boston)) +
geom\_boxplot(aes(x = ``Chicago'', y = Chicago))

\#bring in snowdata tidy
snowdata\_tidy \textless{}- rio::import(``data/snowdata\_tidy.csv'')

\#view a tidy table
View(snowdata\_tidy)

\#Boxplot with ggplot
ggplot(snowdata\_tidy, aes(x = City, y = TotalSnow)) +
geom\_boxplot()

\#Line graphs
ggplot(snowdata\_tidy, aes(x = Winter, y = TotalSnow, group = City)) +
geom\_line()

\#ggplot with colors and points

ggplot(snowdata\_tidy, aes(x = Winter, y = TotalSnow, group = City, color = City)) +
geom\_line()

\#ggplot with colors and points
ggplot(snowdata\_tidy, aes(x = Winter, y = TotalSnow, group = City, color = City)) +
geom\_line() +
geom\_point()

\#Filtered for two years, 1999 and 2000
snowdata\_tidy21 \textless{}- filter(snowdata\_tidy, Winter \textgreater{}= ``1999-2000'')
ggplot(snowdata\_tidy21, aes(x = Winter, y = TotalSnow, group = City, color = City)) +
geom\_line() +
geom\_point()

\#Barplots
ggplot(data = snowdata\_tidy21, aes(x = Winter, y = TotalSnow, group = City, color = City)) +
geom\_col()

\#Not so ugly bars
ggplot(data = snowdata\_tidy21, aes(x = Winter, y = TotalSnow, group = City, fill = City)) +
geom\_col(position = ``dodge'')

\#-------------------------------------------------------------------\#
\#Build a chart - Snow
\#-------------------------------------------------------------------\#

library(ggplot2)
SnowChartBoston \textless{}- ggplot(bostonsnow, aes(x = reorder(Winter, TotalSnow), y = TotalSnow)) +
geom\_bar(stat = ``identity'') +
coord\_flip() +
labs(title = ``Snow'',
subtitle = ``lots of it'',
caption = ``Graphic by Rob Wells'',
x=``Years'',
y=``snow in inches'')
plot(SnowChartBoston)

\#Notes from R for Data Scientists - Wickham
\#\url{https://r4ds.had.co.nz/}

\#Feb.~2 2019
install.packages(`tidyverse')
install.packages(c(``nycflights13'', ``gapminder'', ``Lahman''))

\#If we want to make it clear what package an object comes from, we'll use the package name followed by two colons, like dplyr::mutate(), or
\#nycflights13::flights. This is also valid R code.

library(tidyverse)

\#Do cars with big engines use more fuel than cars with small engines?
\#displ, a car's engine size, in litres.
\#hwy, a car's fuel efficiency on the highway, in miles per gallon (mpg).
\#A car with a low fuel efficiency consumes more fuel than a car with a high fuel efficiency when they travel the same distance.
\#To learn more about mpg, open its help page by running ?mpg.

mpg

mpg \textless{}- as\_data\_frame(mpg)
View(mpg)

ncol(mpg)

\#Create a ggplot
ggplot(data = mpg) +
geom\_point(mapping = aes(x = displ, y = hwy))

\#3.2.3 A graphing template
\#Let's turn this code into a reusable template for making graphs with ggplot2.
\#To make a graph, replace the bracketed sections in the code below with a dataset, a geom function, or a collection of mappings.
\#ggplot(data = ) +
\# (mapping = aes())

ggplot(data = mpg)

\#using color to distinguish class
ggplot(data = mpg) +
geom\_point(mapping = aes(x = displ, y = hwy, color = manufacturer, size=hwy))

str(mpg)

\#MPG categorical = manufacturer model cyl trans drv fl class
\#continuous = disply cty hwy
\#Map a continuous variable to color, size, and shape.
\#How do these aesthetics behave differently for categorical vs.~continuous variables?
\#Answer - they do not come up in discrete blocks by on a spectrum range

\#Color by manufacturer
ggplot(data = mpg) +
geom\_point(mapping = aes(x = displ, y = hwy, color =manufacturer))

\#Color and Size
ggplot(data = mpg) +
geom\_point(mapping = aes(x = displ, y = hwy, color =manufacturer, size=manufacturer))

\#adding size
ggplot(data = mpg) +
geom\_point(mapping = aes(x = displ, y = hwy, size = class, color = class))

\#What does the stroke aesthetic do? What shapes does it work with? (Hint: use ?geom\_point)
ggplot(data = mpg) +
geom\_point(mapping = aes(x = displ, y = hwy, color = hwy))

\#What happens if you map an aesthetic to something other than a variable name,
\#like aes(colour = displ \textless{} 5)? Note, you'll also need to specify x and y.

ggplot(data = mpg) +
geom\_point(mapping = aes(x = displ, y = hwy, color = displ \textless{} 3))

\#It gives you a true false by color

\#Map two variables
\#Example
\#\url{https://stackoverflow.com/questions/3777174/plotting-two-variables-as-lines-using-ggplot2-on-the-same-graph}

\hypertarget{section}{%
\chapter{}\label{section}}

test\_data \textless{}-
data.frame(
var0 = 100 + c(0, cumsum(runif(49, -20, 20))),
var1 = 150 + c(0, cumsum(runif(49, -10, 10))),
date = seq(as.Date(``2002-01-01''), by=``1 month'', length.out=100)
)

ggplot(test\_data, aes(date)) +
geom\_line(aes(y = var0, colour = ``var0'')) +
geom\_line(aes(y = var1, colour = ``var1''))

\#Apply to mpg
ggplot(data=mpg, aes(hwy)) +
geom\_point(aes(y = displ, colour = ``displ'')) +
geom\_point(aes(y = cyl, colour = ``cyl''))

\#Exercise:
\#Exercise with ArkCo\_Income\_2017
\#1. Create a plot chart with the top 10 counties with the greatest percentage of low-income population
\#Your answer should look like this
\url{https://bit.ly/2BgPmyo}

\#2. Create a plot chart with the top 10 counties with the greatest percentage of upper-income population

\hypertarget{r-data-cleaning}{%
\section{\# R Data Cleaning}\label{r-data-cleaning}}

title: ``SFPD Calls for Service\_Feb 23,2020''
author: ``Rob Wells''
date: ``2/23/2020''

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{reporting-on-homelessness-data-analysis-for-journalists}{%
\subsection{Reporting on Homelessness: Data Analysis for Journalists}\label{reporting-on-homelessness-data-analysis-for-journalists}}

\hypertarget{jour-405v-jour-5003-spring-2020}{%
\subsection{Jour 405v, Jour 5003, Spring 2020}\label{jour-405v-jour-5003-spring-2020}}

\includegraphics{Images/UARK logo NEW.png}

\hypertarget{analysis-of-san-francisco-police-calls-for-service-data}{%
\chapter{Analysis of San Francisco Police Calls for Service Data}\label{analysis-of-san-francisco-police-calls-for-service-data}}

\begin{itemize}
\tightlist
\item
  \textbf{Here is the original dataset: 3,048,797 records}
\end{itemize}

\url{https://data.sfgov.org/Public-Safety/Police-Department-Calls-for-Service/hz9m-tj6z/data}

\begin{itemize}
\item
  \textbf{This tutorial uses a subset of this data}

  The Calls for Service were filtered as follows:
  CONTAINS homeless, 915, 919, 920: Downloaded 157,237 records 3/31/16 to 11/30/2019.
  This is 5.1\% of all calls in the broader database.
  File renamed to: SF\_311\_Jan29.xlsx
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{part-1-quick-start}{%
\chapter{Part 1: Quick Start}\label{part-1-quick-start}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(janitor)}
\KeywordTok{library}\NormalTok{(lubridate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'lubridate'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     date, intersect, setdiff, union
\end{verbatim}

Reload Data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF <-}\StringTok{ }\NormalTok{rio}\OperatorTok{::}\KeywordTok{import}\NormalTok{(}\StringTok{"https://github.com/profrobwells/HomelessSP2020/blob/master/Data/SF_311_Jan29.xlsx?raw=true"}\NormalTok{, }\DataTypeTok{which =} \StringTok{"SF Police_Department_Calls_for_"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Clean names, Process dates}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF <-}\StringTok{ }\NormalTok{janitor}\OperatorTok{::}\KeywordTok{clean_names}\NormalTok{(SF)}
\CommentTok{#Process dates}
\NormalTok{SF}\OperatorTok{$}\NormalTok{call_date2 <-}\StringTok{ }\KeywordTok{ymd}\NormalTok{(SF}\OperatorTok{$}\NormalTok{call_date)}
\NormalTok{SF}\OperatorTok{$}\NormalTok{year <-}\StringTok{ }\KeywordTok{year}\NormalTok{(SF}\OperatorTok{$}\NormalTok{call_date2)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Process dates}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Days <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(call_date2) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(call_date2) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Types of Crimes}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Types <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(original_crime_type_name) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(original_crime_type_name) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Calls by Year}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Years <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(year) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(year) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(year))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Actions Taken}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Action <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(disposition) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\hypertarget{part-2-cleaning-analysis}{%
\chapter{Part 2: Cleaning \& Analysis}\label{part-2-cleaning-analysis}}

\begin{itemize}
\tightlist
\item
  \textbf{Question}: How many rows? Columns? Supply a list of the column names
\end{itemize}

nrow(SF)
{[}1{]} 157237
\textgreater{} ncol(SF)
{[}1{]} 14
Process dates, check file types

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(SF)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    157237 obs. of  16 variables:
##  $ crime_id                : num  190040497 190200644 190213959 190271011 190141952 ...
##  $ original_crime_type_name: chr  "919" "Homeless Complaint" "Homeless Complaint" "915" ...
##  $ report_date             : POSIXct, format: "2019-01-04" "2019-01-20" ...
##  $ call_date               : POSIXct, format: "2019-01-04" "2019-01-20" ...
##  $ offense_date            : POSIXct, format: "2019-01-04" "2019-01-20" ...
##  $ call_time               : POSIXct, format: "1899-12-31 06:58:00" "1899-12-31 06:19:00" ...
##  $ call_date_time          : POSIXct, format: "2019-01-04 06:58:00" "2019-01-20 06:19:00" ...
##  $ disposition             : chr  "HAN" "HAN" "ADV" "HAN" ...
##  $ address                 : chr  "400 Block Of Jones St" "8th And Market" "Mission St/24th St" "Alabama St/23rd St" ...
##  $ city                    : chr  "San Francisco" NA "San Francisco" "San Francisco" ...
##  $ state                   : chr  "CA" "CA" "CA" "CA" ...
##  $ agency_id               : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ address_type            : chr  "Premise Address" "Geo-Override" "Intersection" "Intersection" ...
##  $ common_location         : chr  NA NA NA NA ...
##  $ call_date2              : Date, format: "2019-01-04" "2019-01-20" ...
##  $ year                    : num  2019 2019 2019 2019 2019 ...
\end{verbatim}

Examine how we have created a new date and year column and how they are formatted differently than the rest
We can now perform date and year calculations
Create Days Table

\begin{itemize}
\tightlist
\item
  \textbf{Question}: Using the summary() function, describe the minimum, maximum, median and mean of calls in the Days table
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(Days)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    call_date2               n      
##  Min.   :2016-03-31   Min.   : 10  
##  1st Qu.:2017-02-28   1st Qu.: 86  
##  Median :2018-01-29   Median :119  
##  Mean   :2018-01-29   Mean   :117  
##  3rd Qu.:2018-12-30   3rd Qu.:148  
##  Max.   :2019-11-30   Max.   :232
\end{verbatim}

Between March 31, 2016 and Nov.~30, 2019, San Francisco residents placed \textbf{an average 117 calls} to police complaining about homeless people.

\begin{itemize}
\tightlist
\item
  \textbf{Question}: Which day had the most calls? Which day had the least?
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Days }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(n }\OperatorTok{==}\StringTok{ }\DecValTok{232}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
## # Groups:   call_date2 [1]
##   call_date2     n
##   <date>     <int>
## 1 2019-08-15   232
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Days }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(n }\OperatorTok{==}\StringTok{ }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
## # Groups:   call_date2 [1]
##   call_date2     n
##   <date>     <int>
## 1 2016-03-31    10
\end{verbatim}

Examine the types of events

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Types <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(original_crime_type_name) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(original_crime_type_name) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Question}: What are the top five complaints in this data and provide the number of complaints
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Types <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(original_crime_type_name) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(original_crime_type_name) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

Create separate table with just the top five counties' crime rate: dplyr has a ``top\_n'' function that i find handy

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Types <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(original_crime_type_name) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{top_n}\NormalTok{(}\DecValTok{5}\NormalTok{, n) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

Export a table into a spreadsheet (csv is a comma separated file)

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{write.csv}\NormalTok{(Days,}\StringTok{"Days.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Build a table totalling the number of complaints by year

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Years <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(year) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(year) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(year))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{EXERCISE: Grouping by Disposition}
\end{itemize}

Look at the Radio Codes spreadsheet under dispositions

\url{https://data.sfgov.org/api/views/hz9m-tj6z/files/b60ee24c-ae7e-4f0b-a8d5-8f4bd29bf1de?download=true\&filename=Radio\%20Codes\%202016.xlsx}

Total by disposition

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Action <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(disposition) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

Ceate a table with serious infractions described in disposition

Example: Here's a table filtering the dispositions column to show ``no disposition'' or ``gone on arrival''

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Nothing <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(disposition }\OperatorTok{==}\StringTok{ "ND"} \OperatorTok{|}\StringTok{ }\NormalTok{disposition }\OperatorTok{==}\StringTok{ "GOA"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Question}: Create a table with the serious actions including citations and arrests police took in the dispositions
\end{itemize}

Arrest, Cited, Criminal Activation, SF Fire Dept Medical Staff engaged

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Busted <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(disposition }\OperatorTok{==}\StringTok{ "ARR"} \OperatorTok{|}\StringTok{ }\NormalTok{disposition }\OperatorTok{==}\StringTok{ "CIT"} \OperatorTok{|}\StringTok{ }\NormalTok{disposition }\OperatorTok{==}\StringTok{ "CRM"} \OperatorTok{|}\StringTok{ }\NormalTok{disposition }\OperatorTok{==}\StringTok{ "SFD"}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(disposition) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{EXERCISE} - A Basic chart of the crime data
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(Years, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ year, }\DataTypeTok{y =}\NormalTok{ n)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\CommentTok{#coord_flip() +    #this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Homeless Calls Per Year, San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data, 3/2016-11/2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Year"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-26-1.pdf}

A chart using a dplyr filtering language

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Years }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(year }\OperatorTok{>=}\StringTok{ }\DecValTok{2017}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ year, }\DataTypeTok{y =}\NormalTok{ n)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\CommentTok{#coord_flip() +    #this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Homeless Calls After 2017, San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data, 2017-2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Year"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-27-1.pdf}

A more complex filter

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(common_location)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(common_location) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{top_n}\NormalTok{(}\DecValTok{10}\NormalTok{, n) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ common_location, }\DataTypeTok{y =}\NormalTok{ n)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{    }\CommentTok{#this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Popular Spots for Homeless, San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data, 2016-2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Places"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-28-1.pdf}

\begin{itemize}
\tightlist
\item
  \textbf{Question}: Chart the total dispositions.
\end{itemize}

Filter for at least 100 actions. Add color, export image to Blackboard.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Action }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(n }\OperatorTok{>}\StringTok{ }\DecValTok{100}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \KeywordTok{reorder}\NormalTok{(disposition, n), }\DataTypeTok{y =}\NormalTok{ n, }\DataTypeTok{fill=}\NormalTok{n)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{    }\CommentTok{#this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Action on Homeless Calls, San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data, 3/2016-11/2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Action"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-29-1.pdf}

\hypertarget{part-3-cleaning-dispositions}{%
\chapter{Part 3: Cleaning Dispositions}\label{part-3-cleaning-dispositions}}

Making our charts less ugly

The disposition column is in cop-speak. We need to clean it up

Step \#1: Duplicate the column you want to mess with

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF}\OperatorTok{$}\NormalTok{disposition1 <-}\StringTok{ }\NormalTok{SF}\OperatorTok{$}\NormalTok{disposition}
\end{Highlighting}
\end{Shaded}

Rename specific strings. Example:

str\_replace\_all(test.vector, pattern=fixed(`-'), replacement=fixed(`:') )

Details on string manipulation:

\url{https://dereksonderegger.github.io/570L/13-string-manipulation.html}

We can do this to replace ABA with ``Abated''

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF}\OperatorTok{$}\NormalTok{disposition1 <-}\StringTok{ }\KeywordTok{str_replace_all}\NormalTok{(SF}\OperatorTok{$}\NormalTok{disposition1, }\DataTypeTok{pattern=}\KeywordTok{fixed}\NormalTok{(}\StringTok{'ABA'}\NormalTok{), }\DataTypeTok{replacement=}\KeywordTok{fixed}\NormalTok{(}\StringTok{'Abated'}\NormalTok{) )}
\CommentTok{#Again with ADM}
\NormalTok{SF}\OperatorTok{$}\NormalTok{disposition1 <-}\StringTok{ }\KeywordTok{str_replace_all}\NormalTok{(SF}\OperatorTok{$}\NormalTok{disposition1, }\DataTypeTok{pattern=}\KeywordTok{fixed}\NormalTok{(}\StringTok{'ADM'}\NormalTok{), }\DataTypeTok{replacement=}\KeywordTok{fixed}\NormalTok{(}\StringTok{'Admonished'}\NormalTok{) )}
\end{Highlighting}
\end{Shaded}

We can do that 19 times. OR\ldots{}.

Look at this example using a lookup table to replace all the values\\
\url{https://stackoverflow.com/questions/50615116/renaming-character-variables-in-a-column-in-data-frame-r}

Build a table to translate the Cop Speak to English:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dispo_lkup <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DataTypeTok{ABA=}\StringTok{"Abated"}\NormalTok{, }\DataTypeTok{ADM=}\StringTok{"Admonish"}\NormalTok{, }\DataTypeTok{ADV=}\StringTok{"Advised"}\NormalTok{, }\DataTypeTok{ARR=}\StringTok{"Arrest"}\NormalTok{, }\DataTypeTok{CAN=}\StringTok{"Cancel"}\NormalTok{, }\DataTypeTok{CSA=}\StringTok{"CPSA"}\NormalTok{, }
                \DataTypeTok{CIT=}\StringTok{"Cited"}\NormalTok{, }\DataTypeTok{CRM=}\StringTok{"Criminal"}\NormalTok{, }\DataTypeTok{GOA=}\StringTok{"Gone"}\NormalTok{, }\DataTypeTok{HAN=}\StringTok{"Handled"}\NormalTok{, }\DataTypeTok{NCR=}\StringTok{"No_Criminal"}\NormalTok{, }\DataTypeTok{ND=}\StringTok{"No_Dispo"}\NormalTok{, }
                \DataTypeTok{NOM=}\StringTok{"No_Merit"}\NormalTok{, }\DataTypeTok{PAS=}\StringTok{"PlaceSecure"}\NormalTok{, }\DataTypeTok{REP=}\StringTok{"Report"}\NormalTok{, }\DataTypeTok{SFD=}\StringTok{"Medical"}\NormalTok{, }\DataTypeTok{UTL=}\StringTok{"Unfound"}\NormalTok{, }\DataTypeTok{VAS=}\StringTok{"Vehicle_Secure"}\NormalTok{, }\StringTok{'22'}\NormalTok{=}\StringTok{"Cancel"}\NormalTok{)}
\CommentTok{#22="Cancel" was handled differently because it is a numeric value: '22'="Cancel"}
\CommentTok{#This scans "disposition", finds ABA and replaces with Abated, finds ARR, replaces with Arrest, etc}
\NormalTok{SF}\OperatorTok{$}\NormalTok{disposition1 <-}\StringTok{ }\KeywordTok{as.character}\NormalTok{(dispo_lkup[SF}\OperatorTok{$}\NormalTok{disposition])}
\end{Highlighting}
\end{Shaded}

Rerun Action with disposition1

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Action <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(disposition1) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

Compare our renamed variables to the original disposition

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Action <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(disposition1, disposition) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

We have codes not listed on the sheet

NA Not recorded 4339

Get rid of the space

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF}\OperatorTok{$}\NormalTok{disposition <-}\StringTok{ }\KeywordTok{gsub}\NormalTok{(}\StringTok{"Not recorded"}\NormalTok{, }\StringTok{"Not_Recorded"}\NormalTok{, SF}\OperatorTok{$}\NormalTok{disposition)}
\end{Highlighting}
\end{Shaded}

Add to the list

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dispo_lkup <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DataTypeTok{ABA=}\StringTok{"Abated"}\NormalTok{, }\DataTypeTok{ADM=}\StringTok{"Admonish"}\NormalTok{, }\DataTypeTok{ADV=}\StringTok{"Advised"}\NormalTok{, }\DataTypeTok{ARR=}\StringTok{"Arrest"}\NormalTok{, }\DataTypeTok{CAN=}\StringTok{"Cancel"}\NormalTok{, }\DataTypeTok{CSA=}\StringTok{"CPSA"}\NormalTok{, }
                \DataTypeTok{CIT=}\StringTok{"Cited"}\NormalTok{, }\DataTypeTok{CRM=}\StringTok{"Criminal"}\NormalTok{, }\DataTypeTok{GOA=}\StringTok{"Gone"}\NormalTok{, }\DataTypeTok{HAN=}\StringTok{"Handled"}\NormalTok{, }\DataTypeTok{NCR=}\StringTok{"No_Criminal"}\NormalTok{, }\DataTypeTok{ND=}\StringTok{"No_Dispo"}\NormalTok{, }
                \DataTypeTok{NOM=}\StringTok{"No_Merit"}\NormalTok{, }\DataTypeTok{PAS=}\StringTok{"PlaceSecure"}\NormalTok{, }\DataTypeTok{REP=}\StringTok{"Report"}\NormalTok{, }\DataTypeTok{SFD=}\StringTok{"Medical"}\NormalTok{, }\DataTypeTok{UTL=}\StringTok{"Unfound"}\NormalTok{, }
                \DataTypeTok{VAS=}\StringTok{"Vehicle_Secure"}\NormalTok{, }\StringTok{'22'}\NormalTok{=}\StringTok{"Cancel"}\NormalTok{, }\DataTypeTok{Not_Recorded=}\StringTok{"NotRecorded"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Rerun

\hypertarget{section-1}{%
\chapter{}\label{section-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Action <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(disposition1) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

Chart Dispositions

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Action }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(n }\OperatorTok{>}\StringTok{ }\DecValTok{100}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \KeywordTok{reorder}\NormalTok{(disposition1, n), }\DataTypeTok{y =}\NormalTok{ n, }\DataTypeTok{fill=}\NormalTok{n)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{    }\CommentTok{#this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Action on Homeless Calls, San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data, 3/2016-11/2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Action"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-39-1.pdf}
- \textbf{Parse out police codes from narrative: original\_crime\_type\_name}
Look at the Types table: some columns have one code, some have two.
919 2879
915 Sleeper 290

Some are separated by a slash
915/919 161

We need to unpack that
- \textbf{Cleaning Sequence}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#convert all text to lowercase}
\NormalTok{SF}\OperatorTok{$}\NormalTok{crime1 <-}\StringTok{ }\KeywordTok{tolower}\NormalTok{(SF}\OperatorTok{$}\NormalTok{original_crime_type_name)}
\CommentTok{#Replace / with a space}
\NormalTok{SF}\OperatorTok{$}\NormalTok{crime1 <-}\StringTok{ }\KeywordTok{gsub}\NormalTok{(}\StringTok{"/"}\NormalTok{, }\StringTok{" "}\NormalTok{, SF}\OperatorTok{$}\NormalTok{crime1)}
\CommentTok{#Replace '}
\NormalTok{SF}\OperatorTok{$}\NormalTok{crime1 <-}\StringTok{ }\KeywordTok{gsub}\NormalTok{(}\StringTok{"'"}\NormalTok{, }\StringTok{""}\NormalTok{, SF}\OperatorTok{$}\NormalTok{crime1)}
\CommentTok{#fix space in homeless complaint}
\NormalTok{SF}\OperatorTok{$}\NormalTok{crime1 <-}\StringTok{ }\KeywordTok{gsub}\NormalTok{(}\StringTok{"homeless complaint"}\NormalTok{, }\StringTok{"homeless_complaint"}\NormalTok{, SF}\OperatorTok{$}\NormalTok{crime1)}
\CommentTok{#split data into two columns}
\NormalTok{SF <-}\StringTok{ }\KeywordTok{separate}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ SF, }\DataTypeTok{col =}\NormalTok{ crime1, }\DataTypeTok{into =} \KeywordTok{c}\NormalTok{(}\StringTok{"crime2"}\NormalTok{, }\StringTok{"crime3"}\NormalTok{, }\StringTok{"crime4"}\NormalTok{), }\DataTypeTok{sep =} \StringTok{" "}\NormalTok{, }\DataTypeTok{extra =} \StringTok{"merge"}\NormalTok{, }\DataTypeTok{fill =} \StringTok{"right"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Look at the categories now

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Types2 <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(crime2) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(crime2) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Question} Take the top 10 crime categories from Type2\\
  Relabel them from the numeric radio codes into English\\
  Using the technique earlier in ``Build a table to translate the Cop Speak to English''\\
  Relabel the offenses
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{clean <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\DataTypeTok{homeless_complaint=}\StringTok{"homeless_complaint"}\NormalTok{, }\StringTok{'915'}\NormalTok{=}\StringTok{"homeless_call"}\NormalTok{, }\StringTok{'919'}\NormalTok{=}\StringTok{"sit_lying"}\NormalTok{, }\StringTok{'920'}\NormalTok{=}\StringTok{"aggress_solicit"}\NormalTok{, }\StringTok{'915s'}\NormalTok{=}\StringTok{"homeless_call"}\NormalTok{, }\StringTok{'915x'}\NormalTok{=}\StringTok{"homeless_call"}\NormalTok{, }\DataTypeTok{drugs=}\StringTok{"drugs"}\NormalTok{, }\StringTok{'601'}\NormalTok{=}\StringTok{"trespasser"}\NormalTok{,}
           \DataTypeTok{poss=}\StringTok{"poss"}\NormalTok{, }\DataTypeTok{aggressive=}\StringTok{"aggressive"}\NormalTok{, }\StringTok{'811'}\NormalTok{=}\StringTok{"intoxicated"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF}\OperatorTok{$}\NormalTok{crime2 <-}\StringTok{ }\KeywordTok{as.character}\NormalTok{(clean[SF}\OperatorTok{$}\NormalTok{crime2])}
\end{Highlighting}
\end{Shaded}

Look at the categories now

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Types2 <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }\KeywordTok{count}\NormalTok{(crime2) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(crime2) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Question:} Make a chart from your cleaned data
\end{itemize}

Basic chart but with a messed up x axis

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Types2 }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ crime2, }\DataTypeTok{y =}\NormalTok{ n, }\DataTypeTok{fill=}\NormalTok{n)) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{    }\CommentTok{#this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Top 10 Homeless Complaints, San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data, 3/2016-11/2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Complaint"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-45-1.pdf}
Chart with a fixed x axis scale; No values filtered out; Labels added to bars

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Types2 }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(crime2)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\CommentTok{#filter(crime2!=" ") %>%  - a crude alternative to previous line!}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =} \KeywordTok{reorder}\NormalTok{(crime2, n), }\DataTypeTok{y =}\NormalTok{ n, }\DataTypeTok{fill=}\NormalTok{n)) }\OperatorTok{+}\StringTok{ }\CommentTok{#reorder sorts the bars}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ n), }\DataTypeTok{hjust =} \FloatTok{-.1}\NormalTok{, }\DataTypeTok{size =} \DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{limits=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{175000}\NormalTok{)) }\OperatorTok{+}\StringTok{ }\CommentTok{#fixes scientific notation}
\StringTok{  }\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{    }\CommentTok{#this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Top 10 Homeless Complaints, San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data, 3/2016-11/2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Complaint"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-46-1.pdf}

\hypertarget{part-4-using-mutate-pct-calcs}{%
\chapter{Part 4: Using Mutate, Pct Calcs}\label{part-4-using-mutate-pct-calcs}}

mutate - Create new column(s) in the data, or change existing column(s).

mutate() adds new variables and preserves existing

Example:
mtcars \textless{}- as.data.frame(mtcars)
View(mtcars)

mtcars2 \textless{}- mtcars \%\textgreater{}\% as\_tibble() \%\textgreater{}\% mutate(
cyl2 = cyl * 2,
cyl4 = cyl2 * 2
)

Process dates using lubidate

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{yearmo =} \KeywordTok{format}\NormalTok{(call_date, }\StringTok{"%Y-%m"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Chart the number of calls by year and month

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(yearmo) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(yearmo) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ yearmo, }\DataTypeTok{y =}\NormalTok{ n, }\DataTypeTok{fill=}\NormalTok{n)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle=}\DecValTok{90}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\CommentTok{#Changes angle of x axis labels}
\StringTok{  }\CommentTok{#coord_flip() +    #this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Homeless Calls After 2017, San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data by Month 2017-2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Year"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-48-1.pdf}

Percentage change per month

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PCT_CHG_CALLS <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(original_crime_type_name, disposition, address, call_date2, yearmo) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(yearmo) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{difference =}\NormalTok{ (n}\OperatorTok{-}\KeywordTok{lag}\NormalTok{(n))) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{pct_change =}\NormalTok{ (difference}\OperatorTok{/}\KeywordTok{abs}\NormalTok{(}\KeywordTok{lag}\NormalTok{(n)))}\OperatorTok{*}\DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Use grepl to search and tabulate}
\end{itemize}

grep and grepl: see ??grep

\url{http://www.endmemo.com/program/R/grepl.php}

Cleaning Sequence

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#convert all text to lowercase}
\NormalTok{SF}\OperatorTok{$}\NormalTok{crime1 <-}\StringTok{ }\KeywordTok{tolower}\NormalTok{(SF}\OperatorTok{$}\NormalTok{original_crime_type_name)}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Search for term, rename, put in new column called ``cleaned''}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x915 <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"915"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"homeless_complaint"}\NormalTok{)}
\NormalTok{x919 <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"919"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"sitting_lying"}\NormalTok{)}
\NormalTok{xsleep <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"sleep"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"sleep"}\NormalTok{)}
\NormalTok{xaggr <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"aggr"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"aggressive"}\NormalTok{)}
\NormalTok{xdrug <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"drug"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"drug"}\NormalTok{)}
\NormalTok{xhomeless <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"homeless_complaint"}\NormalTok{, crime2)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"homeless_complaint"}\NormalTok{)}
\CommentTok{#Moe, Brooke's Work: }
\NormalTok{xnoise <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"415"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"noise"}\NormalTok{)}
\NormalTok{xposs <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"poss"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"possession"}\NormalTok{)}
\NormalTok{xtrespasser <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"601"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"trespasser"}\NormalTok{)}
\NormalTok{xsolicit <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"920"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"solicit"}\NormalTok{)}
\NormalTok{xinterview <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"909"}\NormalTok{, original_crime_type_name)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"interview"}\NormalTok{)}
\NormalTok{xtent <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"tent"}\NormalTok{, crime1)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned=}\StringTok{"tent"}\NormalTok{)}
\NormalTok{xdog <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"dog"}\NormalTok{, crime1)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned=}\StringTok{"dog"}\NormalTok{)}
\NormalTok{xchopshop <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"chop shop"}\NormalTok{, crime1)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned=}\StringTok{"chopshop"}\NormalTok{)}
\NormalTok{xpanhandling <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"panhandling"}\NormalTok{, crime1)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned=}\StringTok{"panhandling"}\NormalTok{)}
\NormalTok{xmusic <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{ (}\StringTok{"music"}\NormalTok{, crime1)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned=}\StringTok{"music"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Create new dataframe using rbind

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{new_total <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(xhomeless, x915, x919, xaggr, xdrug, xsleep, xnoise, xposs, xtrespasser, xsolicit, xinterview, xtent, xdog,}
\NormalTok{                   xchopshop, xpanhandling, xmusic)}
\end{Highlighting}
\end{Shaded}

Count it up!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Total_Calls_Master <-}\StringTok{ }\NormalTok{new_total }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(cleaned) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\CommentTok{#rename columns}
\KeywordTok{colnames}\NormalTok{(Total_Calls_Master)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{] <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Complaints"}\NormalTok{, }\StringTok{"Number"}\NormalTok{)}
\CommentTok{#export}
\KeywordTok{write_csv}\NormalTok{(Total_Calls_Master, }\StringTok{"Total_Calls_Master.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Make into html table

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#install.packages("kableExtra")}
\KeywordTok{library}\NormalTok{(kableExtra)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'kableExtra'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     group_rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#This makes html tables called "kables"}
\NormalTok{Total_Calls_Master }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{kable}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\StringTok{"striped"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{l|r}
\hline
Complaints & Number\\
\hline
homeless\_complaint & 153895\\
\hline
sitting\_lying & 3282\\
\hline
solicit & 262\\
\hline
trespasser & 100\\
\hline
sleep & 77\\
\hline
interview & 75\\
\hline
drug & 52\\
\hline
noise & 27\\
\hline
aggressive & 18\\
\hline
dog & 12\\
\hline
tent & 9\\
\hline
music & 8\\
\hline
chopshop & 7\\
\hline
panhandling & 5\\
\hline
possession & 5\\
\hline
\end{tabular}
\end{table}

Export from Viewer as .png

\begin{itemize}
\tightlist
\item
  \textbf{Task: Tabulate complaints by day of the week}
\end{itemize}

\url{https://github.com/profrobwells/Data-Analysis-Class-Jour-405v-5003/blob/master/Readings/dealing-with-dates.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{weekday =} \KeywordTok{wday}\NormalTok{(call_date, }\DataTypeTok{label=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{abbr=}\OtherTok{FALSE}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Build a summary table with the days of the week with the greatest
number of calls. Create a graphic. Then build a table to see if the complaints vary by day

Below from Matthew Moore, Katy Seiter, Wells edited

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{weekday =} \KeywordTok{wday}\NormalTok{(call_date, }\DataTypeTok{label=}\OtherTok{TRUE}\NormalTok{, }\DataTypeTok{abbr=}\OtherTok{FALSE}\NormalTok{))}
\NormalTok{Weekday_Count <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(weekday, crime_id) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(weekday) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

Graphic of calls by weekdays

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Weekday_Count }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ weekday, }\DataTypeTok{y =}\NormalTok{ n, }\DataTypeTok{fill=}\NormalTok{n)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle=}\DecValTok{90}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\CommentTok{#Changes angle of x axis labels}
\StringTok{  }\CommentTok{#coord_flip() +    #this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Homeless Calls By Weekday in San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data 2017-2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Moore and Seiter"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Weekday"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-58-1.pdf}

Create a Bubble graphic

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ Weekday_Count) }\OperatorTok{+}\StringTok{ }
\StringTok{  }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{mapping =} \KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ weekday, }\DataTypeTok{y =}\NormalTok{ n, }\DataTypeTok{size =}\NormalTok{ n, }\DataTypeTok{color =}\NormalTok{ n), }\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle=}\DecValTok{90}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Homeless By Weekday in San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data 2017-2019: Source: SFPD"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Moore and Seiter"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Weekday"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-59-1.pdf}

Improved bubble chart

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# ggplot(Weekday_Count, aes(x = weekday, y = n)) +}
\CommentTok{#   xlab("Weekday") +}
\CommentTok{#   ylab("Number of Calls") +}
\CommentTok{#   theme_minimal(base_size = 12, base_family = "Georgia") +}
\CommentTok{#   geom_point(aes(size = n, color = n), alpha = 0.7, show.legend = FALSE) +}
\CommentTok{#   scale_size_area(guide = FALSE, max_size = 15) +}
\CommentTok{#   labs(title = "Homeless By Weekday in San Francisco", }
\CommentTok{#        subtitle = "SF PD Service Call Data 2017-2019: Source: SFPD",}
\CommentTok{#        caption = "Graphic by Moore and Seiter")}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Task \#3: Calls vs Dispositions}
\end{itemize}

What calls resulted in arrests? What calls resulted in citations?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Action2 <-}\StringTok{ }\NormalTok{SF }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(crime_id, original_crime_type_name, disposition) }
\end{Highlighting}
\end{Shaded}

We need to pair the crime type and disposition and then count them

From Michael Adkison:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{callsarrest <-}\StringTok{ }\NormalTok{Action2 }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{(}\StringTok{"ARR"}\NormalTok{, disposition)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{cleaned =} \StringTok{"Arrest"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

To quickly format into percents, load formattable

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#install.packages("formattable")}
\KeywordTok{library}\NormalTok{(formattable)}
\NormalTok{callsarrest2 <-}\StringTok{ }\NormalTok{callsarrest }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(original_crime_type_name, disposition) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(original_crime_type_name) }\OperatorTok{%>%}\StringTok{ }
\CommentTok{#mutate(PctTotal = (n/441)) %>% }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(n))}
\KeywordTok{colnames}\NormalTok{(callsarrest2)[}\DecValTok{1}\OperatorTok{:}\DecValTok{2}\NormalTok{] <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Complaints"}\NormalTok{, }\StringTok{"Arrests"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

Build a table to translate the Cop Speak to English:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{clean <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'Homeless Complaint'}\NormalTok{=}\StringTok{"homeless_complaint"}\NormalTok{, }\DataTypeTok{homeless_complaint=}\StringTok{"homeless_complaint"}\NormalTok{, }\StringTok{'915'}\NormalTok{=}\StringTok{"homeless_complaint"}\NormalTok{, }
           \StringTok{'919'}\NormalTok{=}\StringTok{"Sit_lying"}\NormalTok{, }\StringTok{'920'}\NormalTok{=}\StringTok{"Aggress_solicit"}\NormalTok{, }\StringTok{'915s'}\NormalTok{=}\StringTok{"homeless_complaint"}\NormalTok{, }\StringTok{'915x'}\NormalTok{=}\StringTok{"homeless_complaint"}\NormalTok{, }
           \DataTypeTok{drugs=}\StringTok{"drugs"}\NormalTok{, }\StringTok{'601'}\NormalTok{=}\StringTok{"trespasser"}\NormalTok{, }\DataTypeTok{poss=}\StringTok{"poss"}\NormalTok{, }\DataTypeTok{aggressive=}\StringTok{"aggressive"}\NormalTok{, }\StringTok{'811'}\NormalTok{=}\StringTok{"intoxicated"}\NormalTok{, }
           \StringTok{'Drugs / 915'}\NormalTok{=}\StringTok{"Drugs"}\NormalTok{, }\StringTok{'Drugs/915'}\NormalTok{=}\StringTok{"Drugs"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

This scans ``disposition'', finds ABA and replaces with Abated, finds ARR, replaces with Arrest, etc
callsarrest2\(Complaints <- as.character(clean[callsarrest2\)Complaints{]})

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{callsarrest3 <-}\StringTok{ }\NormalTok{callsarrest2 }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{select}\NormalTok{(Complaints, Arrests) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(Complaints) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{total =} \KeywordTok{sum}\NormalTok{(Arrests)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{PctTotal =}\NormalTok{ (total}\OperatorTok{/}\DecValTok{441}\NormalTok{)) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{arrange}\NormalTok{(}\KeywordTok{desc}\NormalTok{(total))}
\KeywordTok{colnames}\NormalTok{(callsarrest3)[}\DecValTok{2}\NormalTok{] <-}\StringTok{ "Arrests"} 
\NormalTok{callsarrest3}\OperatorTok{$}\NormalTok{PctTotal <-}\StringTok{ }\KeywordTok{percent}\NormalTok{(callsarrest3}\OperatorTok{$}\NormalTok{PctTotal)}
\CommentTok{#This makes kables}
\NormalTok{callsarrest3 }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{kable}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{kable_styling}\NormalTok{(}\StringTok{"striped"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}
\centering
\begin{tabular}{l|r|r}
\hline
Complaints & Arrests & PctTotal\\
\hline
Homeless Complaint & 412 & 93.42\%\\
\hline
915 & 19 & 4.31\%\\
\hline
919 & 4 & 0.91\%\\
\hline
920 & 2 & 0.45\%\\
\hline
601 / 915 & 1 & 0.23\%\\
\hline
915 / 909 & 1 & 0.23\%\\
\hline
Drugs / 915 & 1 & 0.23\%\\
\hline
Drugs/915 & 1 & 0.23\%\\
\hline
\end{tabular}
\end{table}

\hypertarget{part-5-trends-over-time}{%
\chapter{Part 5: Trends over time}\label{part-5-trends-over-time}}

\begin{itemize}
\tightlist
\item
  \textbf{Question}: What were the common days for arrests?
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{select}\NormalTok{(weekday, crime_id, disposition) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{(}\StringTok{"ARR"}\NormalTok{, disposition)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(weekday) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     weekday  n
## 1    Sunday 47
## 2    Monday 63
## 3   Tuesday 79
## 4 Wednesday 77
## 5  Thursday 74
## 6    Friday 56
## 7  Saturday 45
\end{verbatim}

Make bubble chart

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# SF %>%}
\CommentTok{#   select(weekday, crime_id, disposition) %>%}
\CommentTok{#   filter(grepl("ARR", disposition)) %>%}
\CommentTok{#   count(weekday) %>% }
\CommentTok{#   ggplot(aes(x = weekday, y = n)) +}
\CommentTok{#   xlab("Weekday") +}
\CommentTok{#   ylab("Arrests") +}
\CommentTok{#   theme_minimal(base_size = 12, base_family = "Georgia") +}
\CommentTok{#   geom_point(aes(size = n, color = n), alpha = 0.7, show.legend = FALSE) +}
\CommentTok{#   scale_size_area(guide = FALSE, max_size = 15) +}
\CommentTok{#   labs(title = "Homeless Arrests By Weekday in San Francisco", }
\CommentTok{#        subtitle = "SF PD Service Call Data 2017-2019: Source: SFPD",}
\CommentTok{#        caption = "Graphic by Wells") }
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\tightlist
\item
  \textbf{Question}: What is the trend for arrests over the time period?
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{grepl}\NormalTok{(}\StringTok{"ARR"}\NormalTok{, disposition)) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{count}\NormalTok{(yearmo) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(yearmo) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ yearmo, }\DataTypeTok{y =}\NormalTok{ n, }\DataTypeTok{fill=}\NormalTok{n)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =}\NormalTok{ lm, }\DataTypeTok{se=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{color =} \StringTok{"red"}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle=}\DecValTok{90}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\CommentTok{#Changes angle of x axis labels}
\StringTok{  }\CommentTok{#coord_flip() +    #this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Arrest Trends on Homeless Calls in San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"Arrests Based on SF PD Service Call Data by Month 2017-2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Year"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-68-1.pdf}

\begin{itemize}
\tightlist
\item
  \textbf{Question}: What are the hours most likely for complaints?
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#format to hours}
\NormalTok{SF}\OperatorTok{$}\NormalTok{hour <-}\StringTok{ }\KeywordTok{hour}\NormalTok{(SF}\OperatorTok{$}\NormalTok{call_date_time)}
\NormalTok{SF }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{count}\NormalTok{(hour) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{group_by}\NormalTok{(hour) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ hour, }\DataTypeTok{y =}\NormalTok{ n, }\DataTypeTok{fill=}\NormalTok{n)) }\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{show.legend =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{+}
\StringTok{  }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle=}\DecValTok{90}\NormalTok{)) }\OperatorTok{+}
\StringTok{  }\CommentTok{#Changes angle of x axis labels}
\StringTok{  }\CommentTok{#coord_flip() +    #this makes it a horizontal bar chart instead of vertical}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"Hours of Homeless Calls, San Francisco"}\NormalTok{, }
       \DataTypeTok{subtitle =} \StringTok{"SF PD Service Call Data by Month 2017-2019"}\NormalTok{,}
       \DataTypeTok{caption =} \StringTok{"Graphic by Wells"}\NormalTok{,}
       \DataTypeTok{y=}\StringTok{"Number of Calls"}\NormalTok{,}
       \DataTypeTok{x=}\StringTok{"Hour"}\NormalTok{)  }
\end{Highlighting}
\end{Shaded}

\includegraphics{bookdown-demo_files/figure-latex/unnamed-chunk-69-1.pdf}
- \textbf{Question}: Examine some of the charting options on this tutorial and adapt them to this data using any chart you want
\# \url{https://paldhous.github.io/wcsj/2017/}

\hypertarget{section-2}{%
\chapter{--30--}\label{section-2}}

\bibliography{book.bib,packages.bib}

\end{document}
